//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValuationService.ValexService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ws.valex.com.au/soap/lixi/1.3/", ConfigurationName="ValexService.VXWS_ClientPortType")]
    public interface VXWS_ClientPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=acceptQuote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        int acceptQuote(string valex_id, string valfirm_quote_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=acceptQuote", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<int> acceptQuoteAsync(string valex_id, string valfirm_quote_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=cancellationReq" +
            "uest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        int cancellationRequest(string valuationMessage, int reason_id, string comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=cancellationReq" +
            "uest", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<int> cancellationRequestAsync(string valuationMessage, int reason_id, string comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=determineServic" +
            "e", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseXml")]
        string determineService(string valuationMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=determineServic" +
            "e", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseXml")]
        System.Threading.Tasks.Task<string> determineServiceAsync(string valuationMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=fetchSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseMessage")]
        string fetchSettings(string valexId, string loanRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=fetchSettings", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseMessage")]
        System.Threading.Tasks.Task<string> fetchSettingsAsync(string valexId, string loanRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=find", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseXml")]
        string find(string valuationMessage, string searchType, string noOlderThan, bool completedOnly);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=find", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseXml")]
        System.Threading.Tasks.Task<string> findAsync(string valuationMessage, string searchType, string noOlderThan, bool completedOnly);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=findOnWatchlist" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseCode")]
        string findOnWatchlist(string valuationMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=findOnWatchlist" +
            "", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseCode")]
        System.Threading.Tasks.Task<string> findOnWatchlistAsync(string valuationMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=requestValuatio" +
            "nQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseCode")]
        string requestValuationQuery(string valuationMessage, int reasonId, string comment, bool useErrorCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=requestValuatio" +
            "nQuery", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseCode")]
        System.Threading.Tasks.Task<string> requestValuationQueryAsync(string valuationMessage, int reasonId, string comment, bool useErrorCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=subscribe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        int subscribe(string valuationMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=subscribe", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<int> subscribeAsync(string valuationMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseCode")]
        int update(string valuationMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=update", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseCode")]
        System.Threading.Tasks.Task<int> updateAsync(string valuationMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=valuationReques" +
            "t", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseCode")]
        int valuationRequest(string valuationMessage, bool useErrorCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.valex.com.au/soap/lixi/1.3.1/index.php?n=client&method=valuationReques" +
            "t", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseCode")]
        System.Threading.Tasks.Task<int> valuationRequestAsync(string valuationMessage, bool useErrorCodes);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="https://ws.valex.com.au/soap/lixi/1.3/")]
    public partial class vAuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VXWS_ClientPortTypeChannel : ValuationService.ValexService.VXWS_ClientPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VXWS_ClientPortTypeClient : System.ServiceModel.ClientBase<ValuationService.ValexService.VXWS_ClientPortType>, ValuationService.ValexService.VXWS_ClientPortType {
        
        public VXWS_ClientPortTypeClient() {
        }
        
        public VXWS_ClientPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VXWS_ClientPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VXWS_ClientPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VXWS_ClientPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int acceptQuote(string valex_id, string valfirm_quote_id) {
            return base.Channel.acceptQuote(valex_id, valfirm_quote_id);
        }
        
        public System.Threading.Tasks.Task<int> acceptQuoteAsync(string valex_id, string valfirm_quote_id) {
            return base.Channel.acceptQuoteAsync(valex_id, valfirm_quote_id);
        }
        
        public int cancellationRequest(string valuationMessage, int reason_id, string comments) {
            return base.Channel.cancellationRequest(valuationMessage, reason_id, comments);
        }
        
        public System.Threading.Tasks.Task<int> cancellationRequestAsync(string valuationMessage, int reason_id, string comments) {
            return base.Channel.cancellationRequestAsync(valuationMessage, reason_id, comments);
        }
        
        public string determineService(string valuationMessage) {
            return base.Channel.determineService(valuationMessage);
        }
        
        public System.Threading.Tasks.Task<string> determineServiceAsync(string valuationMessage) {
            return base.Channel.determineServiceAsync(valuationMessage);
        }
        
        public string fetchSettings(string valexId, string loanRef) {
            return base.Channel.fetchSettings(valexId, loanRef);
        }
        
        public System.Threading.Tasks.Task<string> fetchSettingsAsync(string valexId, string loanRef) {
            return base.Channel.fetchSettingsAsync(valexId, loanRef);
        }
        
        public string find(string valuationMessage, string searchType, string noOlderThan, bool completedOnly) {
            return base.Channel.find(valuationMessage, searchType, noOlderThan, completedOnly);
        }
        
        public System.Threading.Tasks.Task<string> findAsync(string valuationMessage, string searchType, string noOlderThan, bool completedOnly) {
            return base.Channel.findAsync(valuationMessage, searchType, noOlderThan, completedOnly);
        }
        
        public string findOnWatchlist(string valuationMessage) {
            return base.Channel.findOnWatchlist(valuationMessage);
        }
        
        public System.Threading.Tasks.Task<string> findOnWatchlistAsync(string valuationMessage) {
            return base.Channel.findOnWatchlistAsync(valuationMessage);
        }
        
        public string requestValuationQuery(string valuationMessage, int reasonId, string comment, bool useErrorCodes) {
            return base.Channel.requestValuationQuery(valuationMessage, reasonId, comment, useErrorCodes);
        }
        
        public System.Threading.Tasks.Task<string> requestValuationQueryAsync(string valuationMessage, int reasonId, string comment, bool useErrorCodes) {
            return base.Channel.requestValuationQueryAsync(valuationMessage, reasonId, comment, useErrorCodes);
        }
        
        public int subscribe(string valuationMessage) {
            return base.Channel.subscribe(valuationMessage);
        }
        
        public System.Threading.Tasks.Task<int> subscribeAsync(string valuationMessage) {
            return base.Channel.subscribeAsync(valuationMessage);
        }
        
        public int update(string valuationMessage) {
            return base.Channel.update(valuationMessage);
        }
        
        public System.Threading.Tasks.Task<int> updateAsync(string valuationMessage) {
            return base.Channel.updateAsync(valuationMessage);
        }
        
        public int valuationRequest(string valuationMessage, bool useErrorCodes) {
            return base.Channel.valuationRequest(valuationMessage, useErrorCodes);
        }
        
        public System.Threading.Tasks.Task<int> valuationRequestAsync(string valuationMessage, bool useErrorCodes) {
            return base.Channel.valuationRequestAsync(valuationMessage, useErrorCodes);
        }
    }
}
